[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro-essentials = { git = "https://github.com/YiRanMushroom/proc_macro_essentials", tag = "v1.1.1" }
static_assertions = "1.1.0"


[lib]
proc-macro = true
